googleCode: Here comes google verification code
title: SITE TITLE HERE
desc: SITE DESCRIPTION HERE
keyword: KEYWORD, KEYWORD, KEYWORD

socialmedia:
    facebook: https://www.facebook.com
    instagram: https://www.instagram.com
    twitter: https://www.twitter.com
