googleCode: Here comes google verification code
title: SITE TITLE HERE
desc: SITE DESCRIPTION HERE
keyword: KEYWORD, KEYWORD, KEYWORD

contact:
    address: Jan Haringstraat 2B, 3554XW, UTRECHT
    tel: "+31612220279"
    email: alaa@gmail.com

socialmedia:
    facebook: https://www.facebook.com
    instagram: https://www.instagram.com
    twitter: https://www.twitter.com
