backend:
  name: github
  repo: Alaamasoud/ExpRepo
  
media_folder: "assets/images"


collections:
    #WEB SITE SETTINGS
  - name: "website-settings"
    label: "WEBSITE SETTINGS"
    files:
      - label: "WEBSITE SETTINGS"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "SITE TITLE"
            name: "title"
            widget: "string" 
          - label: "SITE DESCRIPTION"
            name: "desc"
            widget: "string" 
          - label: "SITE KEYWORD"
            name: "keyword"
            widget: "string" 
          - label: "GOOGLE VERIFICATION CODE"
            name: "googleCode"
            widget: "string" 
            
#    HOMEPAGE        
  - name: "homepage"
    label: "HOME PAGE"
    files:
      - label: "SECTIONS"
        name: "sections"
        file: "_data/homepage.yml"
        fields:
          - label: "BANNER"
            name: "banner"
            widget: "object" 
            fields:
              - label: "COVER TITLE"
                name: "coverTitle"
                widget: "string" 
              - label: "COVER SUB TITLE"
                name: "coverSubTitle"
                widget: "string" 
              - label: "COVER CONTENT"
                name: "coverTxt"
                widget: "string" 
              - label: "COVER IMAGE"
                name: "image"
                widget: "image" 
                
          - label: "SECTION CENTERED"
            name: "sectioncentered"
            widget: "object" 
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string" 
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string" 
              - label: "CONTENT"
                name: "txt"
                widget: "string" 
              - label: "BUTTON"
                name: "button1"
                widget: "string" 
                
#    HOMEPAGE        
  - name: "about"
    label: "ABOUT PAGE"
    files:
      - label: "SECTIONS"
        name: "sections"
        file: "_data/about.yml"
        fields:
          - label: "BANNER"
            name: "banner"
            widget: "object" 
            fields:
              - label: "COVER TITLE"
                name: "coverTitle"
                widget: "string" 
              - label: "COVER SUB TITLE"
                name: "coverSubTitle"
                widget: "string" 
              - label: "COVER CONTENT"
                name: "coverTxt"
                widget: "string" 
              - label: "COVER IMAGE"
                name: "image"
                widget: "image" 
                
          - label: "SECTION CENTERED"
            name: "sectioncentered"
            widget: "object" 
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string" 
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string" 
              - label: "CONTENT"
                name: "txt"
                widget: "string" 
              - label: "BUTTON"
                name: "button1"
                widget: "string" 
            