backend:
  name: github
  repo: Alaamasoud/ExpRepo

media_folder: "assets/images"

editor:
 preview: false

#logo_url: http://808studio.nl/assets/images/basic/sprite.svg
#site_url: http://localhost:4000

collections:
    #WEB SITE SETTINGS
  - name: "website-settings"
    label: "WEBSITE SETTINGS"
    files:
      - label: "WEBSITE SETTINGS"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "SITE TITLE"
            name: "title"
            widget: "string"
          - label: "SITE DESCRIPTION"
            name: "desc"
            widget: "text"
          - label: "SITE KEYWORD"
            name: "keyword"
            widget: "string"
          - label: "GOOGLE VERIFICATION CODE"
            name: "googleCode"
            widget: "string"
          - label: "CONTACT INFORMATION"
            name: "contact"
            widget: "object"
            fields:
              - label: "ADDRESS"
                name: "address"
                widget: "string"
              - label: "TEL NUMBER"
                name: "tel"
                widget: "string"
              - label: "EMAIL"
                name: "email"
                widget: "string"
          - label: "SOCIAL MEDIA CHANNELS"
            name: "socialmedia"
            widget: "object"
            fields:
              - label: "FACEBOOK"
                name: "facebook"
                widget: "string"
              - label: "INSTAGRAM"
                name: "instagram"
                widget: "string"
              - label: "TWITTER"
                name: "twitter"
                widget: "string"

#    HOMEPAGE
  - name: "pages"
    label: "PAGES"
    files:
      - label: "HOMEPAGE"
        name: "homepage"
        file: "_data/homepage.yml"
        fields:
          - label: "BANNER"
            name: "banner"
            widget: "object"
            fields:
              - label: "COVER TITLE"
                name: "coverTitle"
                widget: "string"
                required: false
              - label: "COVER SUB TITLE"
                name: "coverSubTitle"
                widget: "string"
                required: false
              - label: "COVER CONTENT"
                name: "coverTxt"
                widget: "markdown"
                required: false
              - label: "COVER COLOR"
                name: "coverColor"
                widget: "select"
                options: ["Light", "Dark", "Dim"]
              - label: "BLOCK POSITION"
                name: "blockPosition"
                widget: "select"
                options: ["Left", "Right"]
              - label: "COVER SIZE"
                name: "coverSize"
                widget: "select"
                options: ["small", "medium", "large"]
              - label: "COVER IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION CENTERED"
            name: "sectioncentered"
            widget: "object"
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "BUTTON"
                name: "button1"
                widget: "string"

          - label: "SECTION IMAGE RIGHT"
            name: "splitRight"
            widget: "object"
            fields:
              - label: "BACKGROUND COLOR"
                name: "bgColor"
                widget: "select"
                options: ["1", "2", "3"]
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION IMAGE LEFT"
            name: "splitLeft"
            widget: "object"
            fields:
              - label: "BACKGROUND COLOR"
                name: "bgColor"
                widget: "select"
                options: ["1", "2", "3"]
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION CONTENT RIGHT"
            name: "contentRight"
            widget: "object"
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "COVER COLOR"
                name: "coverColor"
                widget: "select"
                options: ["Light", "Dark", "Dim"]
              - label: "COVER SIZE"
                name: "coverSize"
                widget: "select"
                options: ["small", "medium", "large"]
              - label: "COVER IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION 8-4"
            name: "8-4"
            widget: "object"
            fields:
              - label: "BACKGROUND COLOR"
                name: "bgColor"
                widget: "select"
                options: ["1", "2", "3"]
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION ICONS BLOCKS"
            name: "iconBlocksSection"
            widget: "object"
            fields:
              - label: "BACKGROUND COLOR"
                name: "bgColor"
                widget: "select"
                options: ["1", "2", "3"]
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "IMAGE POSITION"
                name: "imagePosition"
                widget: "select"
                options: ["Top", "Left"]
              - label: "COLUMNS COUNT"
                name: "columnsCount"
                widget: "select"
                options: ["two", "three", "four"]

          - label: "SECTION CONTENT LEFT"
            name: "contentLeft"
            widget: "object"
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "COVER COLOR"
                name: "coverColor"
                widget: "select"
                options: ["Light", "Dark", "Dim"]
              - label: "COVER SIZE"
                name: "coverSize"
                widget: "select"
                options: ["small", "medium", "large"]
              - label: "COVER IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION POSTS"
            name: "posts"
            widget: "object"
            fields:
              - label: "BACKGROUND COLOR"
                name: "bgColor"
                widget: "select"
                options: ["1", "2", "3"]
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "body"
                name: "body"
                widget: "markdown"
                required: false
              - label: "BLOCK COLOR"
                name: "blockColor"
                widget: "select"
                options: ["White", "1", "2", "3"]
              - label: "COLUMNS COUNT"
                name: "columnsCount"
                widget: "select"
                options: ["two", "three", "four"]
              - label: "ENABLE SLIDER"
                name: "slider"
                widget: "boolean"
                default: false

#PAGE2
      - label: "ABOUT"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "SECTION CENTERED"
            name: "sectioncentered"
            widget: "object"
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string"
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
              - label: "BUTTON"
                name: "button1"
                widget: "string"
          - label: "SECTION CONTENT LEFT"
            name: "contentLeft"
            widget: "object"
            fields:
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "COVER COLOR"
                name: "coverColor"
                widget: "select"
                options: ["Light", "Dark", "Dim"]
              - label: "COVER SIZE"
                name: "coverSize"
                widget: "select"
                options: ["small", "medium", "large"]
              - label: "COVER IMAGE"
                name: "image"
                widget: "image"

          - label: "SECTION IMAGE RIGHT"
            name: "splitRight"
            widget: "object"
            fields:
              - label: "BACKGROUND COLOR"
                name: "bgColor"
                widget: "select"
                options: ["1", "2", "3"]
              - label: "TITLE"
                name: "title"
                widget: "string"
                required: false
              - label: "SUB TITLE"
                name: "subTitle"
                widget: "string"
                required: false
              - label: "CONTENT"
                name: "txt"
                widget: "markdown"
                required: false
              - label: "IMAGE"
                name: "image"
                widget: "image"


#   ICONS BLOCKS SECTION
  - label: "Icons block section"
    name: "iconBlock"
    folder: "_iconBlocks"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "default"
      - label: "TITLE"
        name: "title"
        widget: "string"
      - label: "ICON"
        name: "image_path"
        widget: "image"
      - label: "CONTENT"
        name: "txt"
        widget: "markdown"

#   POSTS BLOCKS SECTION
  - label: "Posts block section"
    name: "posts"
    folder: "_posts"
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "TITLE"
        name: "title"
        widget: "string"
      - label: "IMAGE"
        name: "image"
        widget: "image"
      - label: "body"
        name: "body"
        widget: "markdown"
