backend:
  name: github
  repo: Alaamasoud/ExpRepo
  
media_folder: "assets/images"

collections:
  - name: "website-settings"
    label: "website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "SITE TITLE"
            name: "title"
            widget: "string" 
          - label: "SITE DESCRIPTION"
            name: "desc"
            widget: "string" 
          - label: "SITE KEYWORD"
            name: "keyword"
            widget: "string" 
          - label: "GOOGLE VERIFICATION CODE"
            name: "googleCode"
            widget: "string" 
            
  - name: "homepage"
    label: "HOME PAGE"
    files:
      - label: "section cover"
        name: "site"
        file: "_data/homepage.yml"
        fields:
          - label: "COVER TITLE"
            name: "coverTitle"
            widget: "string" 
          - label: "COVER SUB TITLE"
            name: "coverSubTitle"
            widget: "string" 
          - label: "COVER CONTENT"
            name: "coverTxt"
            widget: "string" 
          - label: "COVER IMAGE"
            name: "image"
            widget: "image" 