backend:
  name: github
  repo: Alaamasoud/ExpRepo/tree/master/jekyll/myTemplate
  
media_folder: "assets/images"

collections:
  - name: "Section Cover"
    label: "Section Cover"
    files:
      - label: "section cover"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Cover Title"
            name: "coverTitle"
            widget: "string" 